version: 0.2

phases:
  install:
    commands:
      - echo "Nessuna installazione necessaria per sito statico"
  build:
    commands:
      - echo "Sincronizzazione file su S3..."
      # Sostituisci NOME-TUO-BUCKET con il nome reale
      - aws s3 sync . s3://portfoliomio --delete --exclude ".git/*"
  post_build:
    commands:
      - echo "Invalidazione cache CloudFront in corso..."
      - aws cloudfront create-invalidation --distribution-id E230URYIR87ZLW --paths "/*"

artifacts:
  files:
    - '**/*'
